services:
  neo4j_db:
    image: neo4j:latest
    volumes: 
      - $HOME/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/secure_password
    ports: 
      - "7474:7474" 
      - "7687:7687"
